=== ridi-bike/ridi-router/rule-examples/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "RouterRules",
  "type": "object",
  "properties": {
    "basic": {
      "default": {
        "no_sharp_turns": {
          "enabled": true,
          "priority": 60,
          "under_deg": 150.0
        },
        "no_short_detours": {
          "enabled": true,
          "min_detour_len_m": 5000.0
        },
        "prefer_same_road": {
          "enabled": true,
          "priority": 30
        },
        "progression_direction": {
          "check_junctions_back": 50,
          "enabled": true
        },
        "progression_speed": {
          "check_steps_back": 1000,
          "enabled": false,
          "last_step_distance_below_avg_with_ratio": 1.3
        },
        "step_limit": 1000000
      },
      "allOf": [
        {
          "$ref": "#/definitions/BasicRules"
        }
      ]
    },
    "highway": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": {
        "$ref": "#/definitions/RulesTagValueAction"
      }
    },
    "smoothness": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": {
        "$ref": "#/definitions/RulesTagValueAction"
      }
    },
    "surface": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": {
        "$ref": "#/definitions/RulesTagValueAction"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "BasicRuleNoSharpTurns": {
      "type": "object",
      "required": [
        "enabled",
        "priority",
        "under_deg"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "priority": {
          "type": "integer",
          "format": "uint8",
          "minimum": 0.0
        },
        "under_deg": {
          "type": "number",
          "format": "float"
        }
      },
      "additionalProperties": false
    },
    "BasicRuleNoShortDetour": {
      "type": "object",
      "required": [
        "enabled",
        "min_detour_len_m"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "min_detour_len_m": {
          "type": "number",
          "format": "float"
        }
      },
      "additionalProperties": false
    },
    "BasicRulePreferSameRoad": {
      "type": "object",
      "required": [
        "enabled",
        "priority"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "priority": {
          "type": "integer",
          "format": "uint8",
          "minimum": 0.0
        }
      },
      "additionalProperties": false
    },
    "BasicRuleProgressDirection": {
      "type": "object",
      "required": [
        "check_junctions_back",
        "enabled"
      ],
      "properties": {
        "check_junctions_back": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "BasicRuleProgressSpeed": {
      "type": "object",
      "required": [
        "check_steps_back",
        "enabled",
        "last_step_distance_below_avg_with_ratio"
      ],
      "properties": {
        "check_steps_back": {
          "type": "integer",
          "format": "uint",
          "minimum": 0.0
        },
        "enabled": {
          "type": "boolean"
        },
        "last_step_distance_below_avg_with_ratio": {
          "type": "number",
          "format": "float"
        }
      },
      "additionalProperties": false
    },
    "BasicRuleStepLimit": {
      "type": "integer",
      "format": "uint32",
      "minimum": 0.0
    },
    "BasicRules": {
      "type": "object",
      "properties": {
        "no_sharp_turns": {
          "default": {
            "enabled": true,
            "priority": 60,
            "under_deg": 150.0
          },
          "allOf": [
            {
              "$ref": "#/definitions/BasicRuleNoSharpTurns"
            }
          ]
        },
        "no_short_detours": {
          "default": {
            "enabled": true,
            "min_detour_len_m": 5000.0
          },
          "allOf": [
            {
              "$ref": "#/definitions/BasicRuleNoShortDetour"
            }
          ]
        },
        "prefer_same_road": {
          "default": {
            "enabled": true,
            "priority": 30
          },
          "allOf": [
            {
              "$ref": "#/definitions/BasicRulePreferSameRoad"
            }
          ]
        },
        "progression_direction": {
          "default": {
            "check_junctions_back": 50,
            "enabled": true
          },
          "allOf": [
            {
              "$ref": "#/definitions/BasicRuleProgressDirection"
            }
          ]
        },
        "progression_speed": {
          "default": {
            "check_steps_back": 1000,
            "enabled": false,
            "last_step_distance_below_avg_with_ratio": 1.3
          },
          "allOf": [
            {
              "$ref": "#/definitions/BasicRuleProgressSpeed"
            }
          ]
        },
        "step_limit": {
          "default": 1000000,
          "allOf": [
            {
              "$ref": "#/definitions/BasicRuleStepLimit"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "RulesTagValueAction": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "action"
          ],
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "avoid"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "action",
            "value"
          ],
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "priority"
              ]
            },
            "value": {
              "type": "integer",
              "format": "uint8",
              "minimum": 0.0
            }
          },
          "additionalProperties": false
        }
      ]
    }
  }
}

=== ridi-bike/ridi-router/rule-examples/rules-default.json
{
	"basic": {
		"prefer_same_road": {
			"enabled": true,
			"priority": 30
		},
		"progression_direction": {
			"enabled": true,
			"check_junctions_back": 50
		},
		"progression_speed": {
			"enabled": false,
			"check_steps_back": 1000,
			"last_step_distance_below_avg_with_ratio": 1.3
		},
		"no_short_detours": {
			"enabled": true,
			"min_detour_len_m": 5000.0
		},
		"no_sharp_turns": {
			"enabled": true,
			"under_deg": 150.0,
			"priority": 60
		}
	},
	"highway": null,
	"surface": null,
	"smoothness": null
}
